AWSTemplateFormatVersion: '2010-09-09'
Description: 'Provides S3 bucket, SNS topic and DynamoDB table infrastructure for ingesting ftacel customer data'

Parameters:

  StageName:
    Type: String
    AllowedValues:
      - dev
      - test
      - prod
    Description: 'The stage of deployment'

Resources:

  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${StageName}-ftacel-customers-ddb'
      AttributeDefinitions:
        - AttributeName: AccountId
          AttributeType: S
        - AttributeName: PhoneNumber1
          AttributeType: S
        - AttributeName: PhoneNumber2
          AttributeType: S
      KeySchema:
        - AttributeName: AccountId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PhoneNumber1Index
          KeySchema:
            - AttributeName: PhoneNumber1
              KeyType: HASH
            - AttributeName: AccountId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: PhoneNumber2Index
          KeySchema:
            - AttributeName: PhoneNumber2
              KeyType: HASH
            - AttributeName: AccountId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: TestIndex
          KeySchema:
            - AttributeName: PhoneNumber1
              KeyType: HASH
            - AttributeName: AccountId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        KMSMasterKeyId: !Ref DynamoKMSKey
        SSEEnabled: true
        SSEType: KMS
      BillingMode: PAY_PER_REQUEST

  CallHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${StageName}-ftacel-callhistory-ddb'
      AttributeDefinitions:
        - AttributeName: PhoneNumber
          AttributeType: S
        - AttributeName: When
          AttributeType: S
      KeySchema:
        - AttributeName: PhoneNumber
          KeyType: HASH
        - AttributeName: When
          KeyType: RANGE
      SSESpecification:
        KMSMasterKeyId: !Ref DynamoKMSKey
        SSEEnabled: true
        SSEType: KMS
      BillingMode: PAY_PER_REQUEST

  IngestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${StageName}-ftacel-ingest-ddb'
      AttributeDefinitions:
        - AttributeName: IngestId
          AttributeType: S
      KeySchema:
        - AttributeName: IngestId
          KeyType: HASH
      SSESpecification:
        KMSMasterKeyId: !Ref DynamoKMSKey
        SSEEnabled: true
        SSEType: KMS
      BillingMode: PAY_PER_REQUEST

  IngestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${StageName}-ftacel-ingest-${AWS::AccountId}'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref IngestBucketKMSKey
              SSEAlgorithm: "aws:kms"
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:*'
            Topic: !Ref IngestS3EventTopic

  IngestBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref IngestBucket
      PolicyDocument:
        Statement:
          - Sid: 'DenyIncorrectEncryptionHeader'
            Effect: Deny
            Principal: '*'
            Action: s3:PutObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref IngestBucket
                - /*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: aws:kms
          - Sid: 'DenyIncorrectKMSIdHeader'
            Effect: Deny
            Principal: '*'
            Action: s3:PutObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref IngestBucket
                - /*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption-aws-kms-key-id: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${IngestBucketKMSKey}'
          - Sid: 'DenyUnEncryptedObjectUploads'
            Effect: Deny
            Principal: '*'
            Action: s3:PutObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref IngestBucket
                - /*
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: true

  IngestBucketKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub '${StageName}-ftacel-ingest-s3-key - encrypts ingested customer data'
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Sub '${StageName}-ftacel-ingest-s3-key'
        Statement:
          -
            Sid: 'Allow administration of the key'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:*'
            Resource: '*'
          -
            Sid: 'Allow use of the key'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'

  IngestBucketKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${StageName}-ftacel-s3-ingest-key'
      TargetKeyId: !Ref IngestBucketKMSKey

  DynamoKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub '${StageName}-ftacel-ingest-dynamo-key - encrypts ingested customer data in DynamoDB'
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Sub '${StageName}-ftacel-ingest-dynamo-key'
        Statement:
          -
            Sid: 'Allow administration of the key'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:*'
            Resource: '*'
          -
            Sid: 'Allow use of the key'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'

  DynamoKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${StageName}-ftacel-ingest-dynamo-key'
      TargetKeyId: !Ref DynamoKMSKey

  GPGKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub '${StageName}-ftacel-ingest-gpg-key - GPG KMS key'
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Sub '${StageName}-ftacel-ingest-gpg-key'
        Statement:
          -
            Sid: 'Allow administration of the key'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:*'
            Resource: '*'
          -
            Sid: 'Allow use of the key'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'

  GPGKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${StageName}-ftacel-ingest-gpg-key'
      TargetKeyId: !Ref GPGKMSKey

  GPGKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub '${StageName}-ftacel-ingest-gpgkey - GPG key'
      Name: !Sub '/${StageName}/ftacel/ingest/${StageName}-ftacel-ingest-gpgkey'
      KmsKeyId: !Ref GPGKMSKey
      SecretString: CHANGEME

  GPGSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub '${StageName}-ftacel-ingest-gpgsecret - GPG passphrase'
      Name: !Sub '/${StageName}/ftacel/ingest/${StageName}-ftacel-ingest-gpgsecret'
      KmsKeyId: !Ref GPGKMSKey
      SecretString: CHANGEME

  IngestS3EventTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${StageName}-ftacel-s3-ingest-topic'
      DisplayName: !Sub '${StageName}-ftacel-s3-ingest-topic'

  IngestS3EventTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: 'AllowBucketToPushNotifications'
          Effect: Allow
          Principal:
            Service: s3.amazonaws.com
          Action: sns:Publish
          Resource: !Ref IngestS3EventTopic
      Topics:
      - !Ref IngestS3EventTopic

Outputs:
  IngestBucketName:
    Description: 'The name of the ingest bucket'
    Value: !Ref IngestBucket
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-s3-bucket'

  IngestS3EventTopicARN:
    Description: 'The ARN of the ingest bucket event SNS topic'
    Value: !Ref 'IngestS3EventTopic'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-sns-topic-arn'

  IngestBucketKMSKeyARN:
    Description: 'The ARN of the ingest KMS key'
    Value: !GetAtt 'IngestBucketKMSKey.Arn'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-s3-kms-arn'

  IngestBucketKMSKeyId:
    Description: 'The id of the ingest KMS key'
    Value: !Ref 'IngestBucketKMSKey'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-s3-kms-id'

  CustomerTableName:
    Description: 'The name of the customer table'
    Value: !Ref 'CustomerTable'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-customers-table'

  CallHistoryTableName:
    Description: 'The name of the call history table'
    Value: !Ref 'CallHistoryTable'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-callhistory-table'

  IngestTableName:
    Description: 'The name of the ingest audit table'
    Value: !Ref 'IngestTable'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-ingests-table'

  DynamoKMSKeyARN:
    Description: 'The ARN of the DynamoDB KMS key'
    Value: !GetAtt 'DynamoKMSKey.Arn'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-dynamo-kms-arn'

  GPGKMSKeyARN:
    Description: 'The ARN of the GPG secret KMS key'
    Value: !GetAtt 'GPGKMSKey.Arn'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-gpg-kms-arn'

  GPGKeyARN:
    Description: 'The arn of the GPG key in Secrets Manager'
    Value: !Ref 'GPGKey'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-gpgkey-arn'

  GPGSecretARN:
    Description: 'The arn of the GPG passphrase in Secrets Manager'
    Value: !Ref 'GPGSecret'
    Export:
      Name: !Sub '${StageName}-ftacel-ingest-gpgsecret-arn'



